# Word Representations and Text/Document Similarity (Count Based)

# Bag of Words

In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk import word_tokenize

In [2]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [3]:
review_1 = 'The movie was good and we really like it'
review_2 = 'the movie was good but the ending was boring'
review_3 = 'we did not like the movie as it was too lengthy'

In [ ]:
review_1_tokens = word_tokenize(review_1)
review_2_tokens = word_tokenize(review_2)
review_3_tokens = word_tokenize(review_3)
print(review_1_tokens)
print(review_2_tokens)
print(review_3_tokens)


['The', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']
['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']
['we', 'did', 'not', 'like', 'the', 'movie', 'as', 'it', 'was', 'too', 'lengthy']


In [ ]:
review_1_tokens = [w.lower() for w in review_1_tokens]
review_2_tokens = [w.lower() for w in review_2_tokens]
review_3_tokens = [w.lower() for w in review_3_tokens]
print(review_1_tokens)
print(review_2_tokens)
print(review_3_tokens)



['the', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']
['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']
['we', 'did', 'not', 'like', 'the', 'movie', 'as', 'it', 'was', 'too', 'lengthy']


In [ ]:
print(set(review_1_tokens))

In [ ]:
review_tokens = set(review_1_tokens).union(set(review_2_tokens)).union(set(review_3_tokens))
print(len(review_tokens))
print(review_tokens)

17
{'boring', 'as', 'lengthy', 'we', 'really', 'movie', 'good', 'was', 'it', 'and', 'like', 'but', 'ending', 'too', 'not', 'the', 'did'}


In [ ]:
review1_dict = dict.fromkeys(review_tokens,0)
review2_dict = dict.fromkeys(review_tokens,0)
review3_dict = dict.fromkeys(review_tokens,0)
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'boring': 0, 'as': 0, 'lengthy': 0, 'we': 0, 'really': 0, 'movie': 0, 'good': 0, 'was': 0, 'it': 0, 'and': 0, 'like': 0, 'but': 0, 'ending': 0, 'too': 0, 'not': 0, 'the': 0, 'did': 0}
{'boring': 0, 'as': 0, 'lengthy': 0, 'we': 0, 'really': 0, 'movie': 0, 'good': 0, 'was': 0, 'it': 0, 'and': 0, 'like': 0, 'but': 0, 'ending': 0, 'too': 0, 'not': 0, 'the': 0, 'did': 0}
{'boring': 0, 'as': 0, 'lengthy': 0, 'we': 0, 'really': 0, 'movie': 0, 'good': 0, 'was': 0, 'it': 0, 'and': 0, 'like': 0, 'but': 0, 'ending': 0, 'too': 0, 'not': 0, 'the': 0, 'did': 0}


In [ ]:
print(review_1_tokens)

In [ ]:
print(review_1_tokens)
print(review_2_tokens)
print(review_3_tokens)

['the', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']
['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']
['we', 'did', 'not', 'like', 'the', 'movie', 'as', 'it', 'was', 'too', 'lengthy']


In [ ]:
#review_1 = 'The movie was good and we really like it'
# review_2 = 'the movie was good but the ending was boring'
# review_3 = 'we did not like the movie as it was too lengthy'
for token in review_1_tokens:
    review1_dict[token]+=1
for token in review_2_tokens:
    review2_dict[token]+=1
for token in review_3_tokens:
    review3_dict[token]+=1

print(review1_dict)
print(review2_dict)
print(review3_dict)

{'boring': 0, 'as': 0, 'lengthy': 0, 'we': 1, 'really': 1, 'movie': 1, 'good': 1, 'was': 1, 'it': 1, 'and': 1, 'like': 1, 'but': 0, 'ending': 0, 'too': 0, 'not': 0, 'the': 1, 'did': 0}
{'boring': 1, 'as': 0, 'lengthy': 0, 'we': 0, 'really': 0, 'movie': 1, 'good': 1, 'was': 2, 'it': 0, 'and': 0, 'like': 0, 'but': 1, 'ending': 1, 'too': 0, 'not': 0, 'the': 2, 'did': 0}
{'boring': 0, 'as': 1, 'lengthy': 1, 'we': 1, 'really': 0, 'movie': 1, 'good': 0, 'was': 1, 'it': 1, 'and': 0, 'like': 1, 'but': 0, 'ending': 0, 'too': 1, 'not': 1, 'the': 1, 'did': 1}


In [ ]:
reviews_dict_df = pd.DataFrame([review1_dict,review2_dict,review3_dict])
reviews_dict_df

boring  as  lengthy  we  really  movie  good  was  it  and  like  but  \
0       0   0        0   1       1      1     1    1   1    1     1    0   
1       1   0        0   0       0      1     1    2   0    0     0    1   
2       0   1        1   1       0      1     0    1   1    0     1    0   

   ending  too  not  the  did  
0       0    0    0    1    0  
1       1    0    0    2    0  
2       0    1    1    1    1

### Removing Stop words

In [ ]:
review_1 = 'The movie was good and we really like it'
review_2 = 'the movie was good but the ending was boring'
review_3 = 'we did not like the movie as it was too lengthy'

In [ ]:
review_1_tokens = word_tokenize(review_1)
review_2_tokens = word_tokenize(review_2)
review_3_tokens = word_tokenize(review_3)

print(review_1_tokens)
print(review_2_tokens)
print(review_3_tokens)


['The', 'movie', 'was', 'good', 'and', 'we', 'really', 'like', 'it']
['the', 'movie', 'was', 'good', 'but', 'the', 'ending', 'was', 'boring']
['we', 'did', 'not', 'like', 'the', 'movie', 'as', 'it', 'was', 'too', 'lengthy']


In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stop_words = set(stopwords.words('english'))
print(len(stop_words))

179


In [ ]:
review_1_tokens = [w.lower() for w in review_1_tokens if not w.lower() in stop_words]
review_2_tokens = [w.lower() for w in review_2_tokens if not w.lower() in stop_words]
review_3_tokens = [w.lower() for w in review_3_tokens if not w.lower() in stop_words]
print(review_1_tokens)
print(review_2_tokens)
print(review_3_tokens)

['movie', 'good', 'really', 'like']
['movie', 'good', 'ending', 'boring']
['like', 'movie', 'lengthy']


In [ ]:
review_tokens = set(review_1_tokens).union(set(review_2_tokens)).union(set(review_3_tokens))
print(len(review_tokens))
print(review_tokens)

7
{'boring', 'like', 'ending', 'lengthy', 'really', 'movie', 'good'}


In [ ]:
review1_dict = dict.fromkeys(review_tokens,0)
review2_dict = dict.fromkeys(review_tokens,0)
review3_dict = dict.fromkeys(review_tokens,0)
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'boring': 0, 'like': 0, 'ending': 0, 'lengthy': 0, 'really': 0, 'movie': 0, 'good': 0}
{'boring': 0, 'like': 0, 'ending': 0, 'lengthy': 0, 'really': 0, 'movie': 0, 'good': 0}
{'boring': 0, 'like': 0, 'ending': 0, 'lengthy': 0, 'really': 0, 'movie': 0, 'good': 0}


In [ ]:
#review_1 = 'The movie was good and we really like it'
for token in review_1_tokens:
    review1_dict[token]+=1
for token in review_2_tokens:
    review2_dict[token]+=1
for token in review_3_tokens:
    review3_dict[token]+=1

In [ ]:
# review_1 = 'The movie was good and we really like it'
# review_2 = 'the movie was good but the ending was boring'
# review_3 = 'we did not like the movie as it was too lengthy'
print(review1_dict)
print(review2_dict)
print(review3_dict)

{'boring': 0, 'like': 1, 'ending': 0, 'lengthy': 0, 'really': 1, 'movie': 1, 'good': 1}
{'boring': 1, 'like': 0, 'ending': 1, 'lengthy': 0, 'really': 0, 'movie': 1, 'good': 1}
{'boring': 0, 'like': 1, 'ending': 0, 'lengthy': 1, 'really': 0, 'movie': 1, 'good': 0}


In [ ]:
reviews_dict_df = pd.DataFrame([review1_dict,review2_dict,review3_dict])
reviews_dict_df

boring  like  ending  lengthy  really  movie  good
0       0     1       0        0       1      1     1
1       1     0       1        0       0      1     1
2       0     1       0        1       0      1     0

This is the Term Count Matrix (TFM)

# Count Vectorizer
sklearn implementation of TFM creation using Bag of Words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
review_list = [review_1,review_2,review_3]
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'we did not like the movie as it was too lengthy']

In [6]:
# count_vect = CountVectorizer()
count_vect = CountVectorizer(stop_words='english')
tfm = count_vect.fit_transform(review_list)
#col_names = count_vect.get_feature_names_out()
col_names = count_vect.get_feature_names_out()


CSR means Compressed Sparse Row, which is a row-wise sparse matrix

In [8]:
print(type(tfm))
print(tfm.toarray())

<class 'scipy.sparse._csr.csr_matrix'>
[[0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]]


In [9]:
print(type(tfm))
print(tfm.toarray())
print(col_names)

<class 'scipy.sparse._csr.csr_matrix'>
[[0 0 0 1 0 1 1 1]
 [1 0 1 1 0 0 1 0]
 [0 1 0 0 1 1 1 0]]
['boring' 'did' 'ending' 'good' 'lengthy' 'like' 'movie' 'really']


In [10]:
a = pd.DataFrame(tfm.toarray(),columns=col_names)
a

boring  did  ending  good  lengthy  like  movie  really
0       0    0       0     1        0     1      1       1
1       1    0       1     1        0     0      1       0
2       0    1       0     0        1     1      1       0

In [ ]:
# review_1 = 'The movie was good and we really like it'
# review_2 = 'the movie was good but the ending was boring'
# review_3 = 'we did not like the movie as it was too lengthy'

# TF-IDF

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
tf_vect = TfidfVectorizer(min_df=1, lowercase=True, stop_words='english')

In [13]:
review_list

['The movie was good and we really like it',
 'the movie was good but the ending was boring',
 'we did not like the movie as it was too lengthy']

In [14]:
tf_matrix = tf_vect.fit_transform(review_list)
tf_names = tf_vect.get_feature_names_out()
print(type(tf_matrix))
print(tf_matrix.shape)
print(tf_matrix.toarray())
print(tf_names)

<class 'scipy.sparse._csr.csr_matrix'>
(3, 8)
[[0.         0.         0.         0.4804584  0.         0.4804584
  0.37311881 0.63174505]
 [0.5844829  0.         0.5844829  0.44451431 0.         0.
  0.34520502 0.        ]
 [0.         0.5844829  0.         0.         0.5844829  0.44451431
  0.34520502 0.        ]]
['boring' 'did' 'ending' 'good' 'lengthy' 'like' 'movie' 'really']


In [15]:

tf_df = pd.DataFrame(tf_matrix.toarray(),columns=tf_names)
tf_df

boring       did    ending      good   lengthy      like     movie  \
0  0.000000  0.000000  0.000000  0.480458  0.000000  0.480458  0.373119   
1  0.584483  0.000000  0.584483  0.444514  0.000000  0.000000  0.345205   
2  0.000000  0.584483  0.000000  0.000000  0.584483  0.444514  0.345205   

     really  
0  0.631745  
1  0.000000  
2  0.000000

In [ ]:
review_list

In [ ]:
# countvectorizer
a

# Document Similarity Estimation using TF-IDF

In [16]:
doc0 = 'Natural Language Processing is the study of making a machine understand and generate languages like humans'
doc1 = 'Cricket is a sports played with a bat and a ball. It is not played in many countries'
doc2 = 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy'
doc3 = 'Football is a sport played in almost all countries of the world. It is played by kicking a ball'

documents = [doc0, doc1, doc2, doc3]
documents

['Natural Language Processing is the study of making a machine understand and generate languages like humans',
 'Cricket is a sports played with a bat and a ball. It is not played in many countries',
 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy',
 'Football is a sport played in almost all countries of the world. It is played by kicking a ball']

In [17]:
tf_vect_docs = TfidfVectorizer(min_df=1, lowercase=True, stop_words='english')
tf_matrix_docs = tf_vect_docs.fit_transform(documents)
tf_colnames = tf_vect_docs.get_feature_names_out()
tf_df = pd.DataFrame(tf_matrix_docs.toarray(),columns=tf_colnames)
tf_df

ball       bat  cornerstone  countries   cricket     easy  evolution  \
0  0.00000  0.000000      0.00000    0.00000  0.000000  0.00000    0.00000   
1  0.30392  0.385484      0.00000    0.30392  0.385484  0.00000    0.00000   
2  0.00000  0.000000      0.34604    0.00000  0.000000  0.34604    0.34604   
3  0.28358  0.000000      0.00000    0.28358  0.000000  0.00000    0.00000   

   football  generate    human  ...   machine    making   natural    played  \
0  0.000000  0.324676  0.00000  ...  0.255978  0.255978  0.324676  0.000000   
1  0.000000  0.000000  0.00000  ...  0.000000  0.000000  0.000000  0.607841   
2  0.000000  0.000000  0.34604  ...  0.272822  0.272822  0.000000  0.000000   
3  0.359685  0.000000  0.00000  ...  0.000000  0.000000  0.000000  0.567160   

   processing     sport    sports     study  understand     world  
0    0.324676  0.000000  0.000000  0.255978    0.324676  0.000000  
1    0.000000  0.000000  0.385484  0.000000    0.000000  0.000000  
2    0.000000  0.000000  0.000000  0.272822    0.000000  0.000000  
3    0.000000  0.359685  0.000000  0.000000    0.000000  0.359685  

[4 rows x 25 columns]

In [ ]:
print(tf_df.shape)

### Calculating the document similarities
* Cosine similarity is a metric used to measure how similar the documents are irrespective of their size. Mathematically, it measures the cosine of the angle between two vectors projected in a multi-dimensional space
* The cosine similarity is advantageous because even if the two similar documents are far apart by the Euclidean distance (due to the size of the document), chances are they may still be oriented closer together. The smaller the angle, higher the cosine similarity

In [18]:
from sklearn.metrics.pairwise import cosine_similarity as c_sim

In [19]:
print(type(tf_matrix_docs))
print(tf_matrix_docs.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(4, 25)


In [20]:
myarr = tf_matrix_docs[0].toarray()
type(myarr), myarr.shape

(numpy.ndarray, (1, 25))

In [21]:
tf_matrix_docs[0].toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.32467583, 0.        ,
        0.32467583, 0.        , 0.32467583, 0.25597815, 0.32467583,
        0.25597815, 0.25597815, 0.32467583, 0.        , 0.32467583,
        0.        , 0.        , 0.25597815, 0.32467583, 0.        ]])

In [ ]:
# doc0 = 'Natural Language Processing is the study of making a machine understand and generate languages like humans'
# doc1 = 'Cricket is a sports played with a bat and a ball. It is not played in many countries'
# doc2 = 'Languages are the cornerstone of human evolution. Making a machine study languages is not easy'
# doc3 = 'Football is a sport played in almost all countries of the world. It is played by kicking a ball'


In [22]:
c_sim(tf_matrix_docs[0], tf_matrix_docs[2])

array([[0.34918271]])

In [23]:
c_sim(tf_matrix_docs[1], tf_matrix_docs[2])

array([[0.]])

In [24]:
c_sim(tf_matrix_docs[1], tf_matrix_docs[3])

array([[0.51711443]])

In [25]:
c_sim(tf_matrix_docs[0], tf_matrix_docs[3])

array([[0.]])

In [26]:
c_sim(tf_matrix_docs[0], tf_matrix_docs[0])

array([[1.]])